---
abstract: 'Convert numbers between various bases'
author:
  - 'Ken Williams <kwilliams@cpan.org>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-BaseCalc
requires:
  Carp: 0
  vars: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Math-BaseCalc
  repository: http://perl-math-basecalc.googlecode.com/svn/trunk
version: 1.014
