---
name: Math-BaseCalc
version: 1.012
author:
  - 'Ken Williams, ken@forum.swarthmore.edu'
abstract: Convert numbers between various bases
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
provides:
  Math::BaseCalc:
    file: lib/Math/BaseCalc.pm
    version: 1.012
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
