---
name: Math-BaseCalc
version: 1.013
author:
  - 'Ken Williams, ken@forum.swarthmore.edu'
abstract: Convert numbers between various bases
license: perl
resources:
  homepage: http://code.google.com/p/perl-math-basecalc
  license: http://dev.perl.org/licenses/
  repository: http://perl-math-basecalc.googlecode.com/svn
build_requires:
  Test::More: 0
provides:
  Math::BaseCalc:
    file: lib/Math/BaseCalc.pm
    version: 1.013
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
